platform :ios, '10.0'

use_frameworks!

# Install dependencies from orinal podpsec to build the framework
target 'ApolloCommonsAgentInfo' do
  pod 'ApolloCommonsJSONParsing', :podspec => "../CategoryFramework/ApolloCommonsJSONParsing.podspec"
end
